-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 13:48:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sleekshift
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sleekshift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sleekshift` DEFAULT CHARACTER SET utf8 ;
USE `sleekshift` ;

-- -----------------------------------------------------
-- Table `sleekshift`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(70) NULL,
  `phone_number` VARCHAR(50) NULL,
  `profile_image_location` VARCHAR(512) NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`special_days_timing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`special_days_timing` (
  `id_special_days_timing` INT NOT NULL,
  `special_days_week` INT NULL,
  `sun_start_time` TIME NULL,
  `sun_close_time` TIME NULL,
  `sat_start_time` TIME NULL,
  `sat_close_time` TIME NULL,
  `fri_start_time` TIME NULL,
  `fri_close_time` TIME NULL,
  PRIMARY KEY (`id_special_days_timing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`company_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`company_details` (
  `id_company` INT NOT NULL AUTO_INCREMENT,
  `comapny_name` VARCHAR(70) NULL,
  `employer_name` VARCHAR(100) NULL,
  `company_address` VARCHAR(100) NULL,
  `city` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  `phone_number` VARCHAR(50) NULL,
  `email` VARCHAR(70) NULL,
  `website` VARCHAR(100) NULL,
  `profile_image_location` VARCHAR(512) NULL,
  `number_of_employees` INT NULL,
  `days_open_week` INT NULL,
  `office_start_time` TIME NULL,
  `office_closing_time` TIME NULL,
  `special_days_timing_id_special_days_timing` INT NOT NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_company`, `special_days_timing_id_special_days_timing`, `users_id_users`),
  UNIQUE INDEX `idowner_UNIQUE` (`id_company` ASC),
  INDEX `fk_company_details_special_days_timing1_idx` (`special_days_timing_id_special_days_timing` ASC),
  INDEX `fk_company_details_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_company_details_special_days_timing1`
    FOREIGN KEY (`special_days_timing_id_special_days_timing`)
    REFERENCES `sleekshift`.`special_days_timing` (`id_special_days_timing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_details_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `sleekshift`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`employment_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`employment_details` (
  `id_employment_details` INT NOT NULL AUTO_INCREMENT,
  `current_employer` VARCHAR(100) NULL,
  `date_joining` DATETIME NULL,
  `employee_id` VARCHAR(50) NULL,
  `job_title` VARCHAR(50) NULL,
  `apply_for_approval` TINYINT(1) NULL,
  `users_id_users` INT NOT NULL,
  `company_details_id_company` INT NOT NULL,
  `duty_hours_week` INT NULL,
  `rate_per_hours` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id_employment_details`, `users_id_users`, `company_details_id_company`),
  INDEX `fk_employment_details_users_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_employment_details_users`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `sleekshift`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_monday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_monday` (
  `id_schedule_monday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_monday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_monday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_monday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_wednesday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_wednesday` (
  `id_schedule_wednesday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_wednesday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_wednesday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_wednesday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_tuesday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_tuesday` (
  `id_schedule_tuesday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_tuesday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_tuesday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_tuesday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_thursday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_thursday` (
  `id_schedule_thursday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_thursday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_thursday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_thursday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_friday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_friday` (
  `id_schedule_friday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_friday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_friday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_friday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_saturday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_saturday` (
  `id_schedule_saturday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_saturday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_saturday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_saturday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_sunday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_sunday` (
  `id_schedule_sunday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_schedule_sunday`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_schedule_sunday_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_schedule_sunday_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`employee_salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`employee_salaries` (
  `id_employee_salaries` INT NOT NULL,
  `hours_worked_current_week` INT NULL,
  `total_worked_hours` INT NULL,
  `salary_current_week` DECIMAL(15,2) NULL,
  `payable_by` DATE NULL,
  `current_week` INT NULL,
  `salary_received_on` DATETIME NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_employee_salaries`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_employee_salaries_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_employee_salaries_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
