-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 21:18:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sleekshift
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sleekshift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sleekshift` DEFAULT CHARACTER SET utf8 ;
USE `sleekshift` ;

-- -----------------------------------------------------
-- Table `sleekshift`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(70) NULL,
  `phone_number` VARCHAR(50) NULL,
  `profile_image_location` VARCHAR(512) NULL,
  `user_active` TINYINT NULL,
  `user_signout` TINYINT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`company_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`company_details` (
  `id_company` INT NOT NULL AUTO_INCREMENT,
  `comapny_name` VARCHAR(70) NULL,
  `employer_name` VARCHAR(100) NULL,
  `company_address` VARCHAR(100) NULL,
  `city` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  `phone_number` VARCHAR(50) NULL,
  `email` VARCHAR(70) NULL,
  `website` VARCHAR(100) NULL,
  `profile_image_location` VARCHAR(512) NULL,
  `number_of_employees` INT NULL,
  `days_open_week` INT NULL,
  `office_start_time` TIME NULL,
  `office_closing_time` TIME NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_company`, `users_id_users`),
  UNIQUE INDEX `idowner_UNIQUE` (`id_company` ASC),
  INDEX `fk_company_details_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_company_details_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `sleekshift`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`employment_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`employment_details` (
  `id_employment_details` INT NOT NULL AUTO_INCREMENT,
  `current_employer` VARCHAR(100) NULL,
  `date_joining` DATETIME NULL,
  `employee_id` VARCHAR(50) NULL,
  `job_title` VARCHAR(50) NULL,
  `apply_for_approval` TINYINT(1) NULL,
  `users_id_users` INT NOT NULL,
  `company_details_id_company` INT NOT NULL,
  `duty_hours_week` INT NULL,
  `rate_per_hours` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id_employment_details`, `users_id_users`, `company_details_id_company`),
  INDEX `fk_employment_details_users_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_employment_details_users`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `sleekshift`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_check` (
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  `employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`employment_details_id_employment_details`, `employment_details_users_id_users`, `employment_details_company_details_id_company`),
  CONSTRAINT `fk_table1_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users` , `company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_monday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_monday` (
  `id_schedule_monday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_monday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_monday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_monday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_wednesday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_wednesday` (
  `id_schedule_wednesday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_wednesday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_wednesday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_wednesday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_tuesday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_tuesday` (
  `id_schedule_tuesday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_tuesday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_tuesday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_tuesday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_thursday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_thursday` (
  `id_schedule_thursday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_thursday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_thursday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_thursday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_friday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_friday` (
  `id_schedule_friday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_friday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_friday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_friday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_saturday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_saturday` (
  `id_schedule_saturday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_saturday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_saturday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_saturday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`schedule_sunday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`schedule_sunday` (
  `id_schedule_sunday` INT NOT NULL,
  `is_open` TINYINT(1) NULL,
  `twelve_am` VARCHAR(50) NULL,
  `one_am` VARCHAR(45) NULL,
  `two_am` VARCHAR(45) NULL,
  `three_am` VARCHAR(45) NULL,
  `four_am` VARCHAR(45) NULL,
  `five_am` VARCHAR(45) NULL,
  `six_am` VARCHAR(45) NULL,
  `seven_am` VARCHAR(45) NULL,
  `eight_am` VARCHAR(45) NULL,
  `nine_am` VARCHAR(45) NULL,
  `ten_am` VARCHAR(45) NULL,
  `eleven_am` VARCHAR(45) NULL,
  `twelve_pm` VARCHAR(45) NULL,
  `one_pm` VARCHAR(45) NULL,
  `two_pm` VARCHAR(45) NULL,
  `three_pm` VARCHAR(45) NULL,
  `four_pm` VARCHAR(45) NULL,
  `five_pm` VARCHAR(45) NULL,
  `six_pm` VARCHAR(45) NULL,
  `seven_pm` VARCHAR(45) NULL,
  `eight_pm` VARCHAR(45) NULL,
  `nine_pm` VARCHAR(45) NULL,
  `ten_pm` VARCHAR(45) NULL,
  `eleven_pm` VARCHAR(45) NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_schedule_sunday`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_schedule_sunday_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_schedule_sunday_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`employee_salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`employee_salaries` (
  `id_employee_salaries` INT NOT NULL,
  `hours_worked_current_week` INT NULL,
  `total_worked_hours` INT NULL,
  `salary_current_week` DECIMAL(15,2) NULL,
  `payable_by` DATE NULL,
  `current_week` INT NULL,
  `salary_received_on` DATETIME NULL,
  `employment_details_id_employment_details` INT NOT NULL,
  `employment_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_employee_salaries`, `employment_details_id_employment_details`, `employment_details_users_id_users`),
  INDEX `fk_employee_salaries_employment_details1_idx` (`employment_details_id_employment_details` ASC, `employment_details_users_id_users` ASC),
  CONSTRAINT `fk_employee_salaries_employment_details1`
    FOREIGN KEY (`employment_details_id_employment_details` , `employment_details_users_id_users`)
    REFERENCES `sleekshift`.`employment_details` (`id_employment_details` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`reschedule_request_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`reschedule_request_details` (
  `id_reschedule_request_details` INT NOT NULL,
  `date_created` DATETIME NULL,
  `requested_to` VARCHAR(50) NULL,
  `requested_from` VARCHAR(50) NULL,
  `is_accept` TINYINT NULL,
  `is_reject` TINYINT NULL,
  `description` VARCHAR(500) NULL,
  `rescedule_spot` DATETIME NULL,
  `accepted_on` DATETIME NULL,
  `rejected_on` DATETIME NULL,
  `schedule_check_employment_details_id_employment_details` INT NOT NULL,
  `schedule_check_employment_details_users_id_users` INT NOT NULL,
  `schedule_check_employment_details_company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_reschedule_request_details`, `schedule_check_employment_details_id_employment_details`, `schedule_check_employment_details_users_id_users`, `schedule_check_employment_details_company_details_id_company`),
  INDEX `fk_reschedule_request_details_schedule_check1_idx` (`schedule_check_employment_details_id_employment_details` ASC, `schedule_check_employment_details_users_id_users` ASC, `schedule_check_employment_details_company_details_id_company` ASC),
  CONSTRAINT `fk_reschedule_request_details_schedule_check1`
    FOREIGN KEY (`schedule_check_employment_details_id_employment_details` , `schedule_check_employment_details_users_id_users` , `schedule_check_employment_details_company_details_id_company`)
    REFERENCES `sleekshift`.`schedule_check` (`employment_details_id_employment_details` , `employment_details_users_id_users` , `employment_details_company_details_id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`notification` (
  `id_notification` INT NOT NULL,
  `date_created` DATETIME NULL,
  `recipient_name` VARCHAR(50) NULL,
  `sender_name` VARCHAR(50) NULL,
  `description` VARCHAR(500) NULL,
  `reschedule_request_details_id_reschedule_request_details` INT NOT NULL,
  PRIMARY KEY (`id_notification`, `reschedule_request_details_id_reschedule_request_details`),
  INDEX `fk_notification_reschedule_request_details1_idx` (`reschedule_request_details_id_reschedule_request_details` ASC),
  CONSTRAINT `fk_notification_reschedule_request_details1`
    FOREIGN KEY (`reschedule_request_details_id_reschedule_request_details`)
    REFERENCES `sleekshift`.`reschedule_request_details` (`id_reschedule_request_details`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`company_security_employ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`company_security_employ` (
  `id_company_security_employ` INT NOT NULL,
  `security_key` VARCHAR(10) NULL,
  `date_created` DATETIME NULL,
  `company_details_id_company` INT NOT NULL,
  `company_details_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_company_security_employ`, `company_details_id_company`, `company_details_users_id_users`),
  INDEX `fk_company_security_employ_company_details1_idx` (`company_details_id_company` ASC, `company_details_users_id_users` ASC),
  CONSTRAINT `fk_company_security_employ_company_details1`
    FOREIGN KEY (`company_details_id_company` , `company_details_users_id_users`)
    REFERENCES `sleekshift`.`company_details` (`id_company` , `users_id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`forgot_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`forgot_password` (
  `id_forgot_password` INT NOT NULL,
  `veritication_code` INT NULL,
  `date_created_` DATETIME NULL,
  `is_expired` TINYINT NULL,
  `is_email_sent` VARCHAR(50) NULL,
  `email_details` VARCHAR(500) NULL,
  `users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_forgot_password`, `users_id_users`),
  INDEX `fk_forgot_password_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_forgot_password_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `sleekshift`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sleekshift`.`company_activation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sleekshift`.`company_activation` (
  `id_company_activation` INT NOT NULL,
  `is_activated` TINYINT NULL,
  `date_activated` DATETIME NULL,
  `is_deactivated` TINYINT NULL,
  `date_deactivated` DATETIME NULL,
  `comment` VARCHAR(500) NULL,
  `company_details_id_company` INT NOT NULL,
  PRIMARY KEY (`id_company_activation`, `company_details_id_company`),
  INDEX `fk_company_activation_company_details1_idx` (`company_details_id_company` ASC),
  CONSTRAINT `fk_company_activation_company_details1`
    FOREIGN KEY (`company_details_id_company`)
    REFERENCES `sleekshift`.`company_details` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
